### PR TITLE
Fix make_numbered_dir on case-insensitive filesystems.

### PR DESCRIPTION
**Pull request by dnozay**
See https://github.com/pytest-dev/pytest/issues/708

### CODE REVIEW

**Comment by dnozay** [comment]
close/reopen to trigger travis build

**Comment by dnozay** [comment]
I triggered the build due to a flaky test (unrelated):

- https://travis-ci.org/pytest-dev/py/builds/228398450 (pass)
- https://travis-ci.org/pytest-dev/py/builds/228402392 (fail)
- https://travis-ci.org/pytest-dev/py/builds/228404619 (pass)

**Comment by dnozay** [comment]
@RonnyPfannschmidt, can you please do a release?

**Comment by nicoddemus** [comment]
@dnozay `1.4.34` is out, thanks for the PR.

**Pull request merged**
