### PR TITLE
bump version to 1.4.33

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by pelme** [comment]
Is there anything I can do to help to get 1.4.33 released? I'd be happy to do the release if that would be helpful.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt took the liberty of creating the packages and pushing them to my index. The jobs are running now:

* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-tester/build/1.0.32)
* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-tester/builds/199805416)

If they pass can we push the release to PyPI?

**Comment by nicoddemus** [comment]
Ouch, it seems all `svn` tests are breaking horribly.

**Comment by RonnyPfannschmidt** [comment]
Ignore svn

**Comment by nicoddemus** [comment]
But do you know why is it failing? `master` is passing fine on Travis.

**Comment by nicoddemus** [comment]
Should we make a release?

**Comment by RonnyPfannschmidt** [comment]
atm i dont care

**Comment by nicoddemus** [comment]
OK I will make a release later then.

**Comment by nicoddemus** [comment]
Closed in favor of #114

**Pull request closed without merging**
