### PR TITLE
typing: fix _SectionWrapper.items: uses str for values always

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Review by bluetech — CHANGES_REQUESTED** [review]
Good catch! The code is a little confusing there.

Actually there are a few more `Optional`s we can remove:

```diff
diff --git a/py/iniconfig.pyi b/py/iniconfig.pyi
index 79b5e6ad..e40d309e 100644
--- a/py/iniconfig.pyi
+++ b/py/iniconfig.pyi
@@ -14,10 +14,10 @@ class _SectionWrapper:
     config: Final[IniConfig]
     name: Final[str]
     def __init__(self, config: IniConfig, name: str) -> None: ...
-    def __getitem__(self, key: str) -> Optional[str]: ...
+    def __getitem__(self, key: str) -> str: ...
     def __iter__(self) -> Iterator[str]: ...
-    def get(self, key: str, default: _D = ..., convert: Callable[[Optional[str]], _T] = ...) -> Union[_T, _D]: ...
-    def items(self) -> Iterator[Tuple[str, Optional[str]]]: ...
+    def get(self, key: str, default: _D = ..., convert: Callable[[str], _T] = ...) -> Union[_T, _D]: ...
+    def items(self) -> Iterator[Tuple[str, str]]: ...
     def lineof(self, name: str) -> Optional[int]: ...
 
 class IniConfig:
@@ -27,5 +27,5 @@ class IniConfig:
     def __contains__(self, arg: str) -> bool: ...
     def __getitem__(self, name: str) -> _SectionWrapper: ...
     def __iter__(self) -> Iterator[_SectionWrapper]: ...
-    def get(self, section: str, name: str, default: _D = ..., convert: Callable[[Optional[str]], _T] = ...) -> Union[_T, _D]: ...
+    def get(self, section: str, name: str, default: _D = ..., convert: Callable[[str], _T] = ...) -> Union[_T, _D]: ...
     def lineof(self, section: str, name: Optional[str] = ...) -> Optional[int]: ...
```

**Comment by bluetech** [comment]
Oops, forgot also

```diff
 class IniConfig:
     path: Final[str]
-    sections: Final[Mapping[str, Mapping[str, Optional[str]]]]
+    sections: Final[Mapping[str, Mapping[str, str]]]
```

**Comment by blueyed** [comment]
@bluetech 
Thanks for reviewing - your patch does not apply to the PR branch.
Please just push it yourself here.

**Comment by bluetech** [comment]
Sorry, it never works for me. Here is the diff again:

```diff
diff --git a/py/iniconfig.pyi b/py/iniconfig.pyi
index 6ed529c4..29332247 100644
--- a/py/iniconfig.pyi
+++ b/py/iniconfig.pyi
@@ -14,18 +14,18 @@ class _SectionWrapper:
     config: Final[IniConfig]
     name: Final[str]
     def __init__(self, config: IniConfig, name: str) -> None: ...
-    def __getitem__(self, key: str) -> Optional[str]: ...
+    def __getitem__(self, key: str) -> str: ...
     def __iter__(self) -> Iterator[str]: ...
-    def get(self, key: str, default: _D = ..., convert: Callable[[Optional[str]], _T] = ...) -> Union[_T, _D]: ...
+    def get(self, key: str, default: _D = ..., convert: Callable[[str], _T] = ...) -> Union[_T, _D]: ...
     def items(self) -> Iterator[Tuple[str, str]]: ...
     def lineof(self, name: str) -> Optional[int]: ...
 
 class IniConfig:
     path: Final[str]
-    sections: Final[Mapping[str, Mapping[str, Optional[str]]]]
+    sections: Final[Mapping[str, Mapping[str, str]]]
     def __init__(self, path: str, data: Optional[str] = None): ...
     def __contains__(self, arg: str) -> bool: ...
     def __getitem__(self, name: str) -> _SectionWrapper: ...
     def __iter__(self) -> Iterator[_SectionWrapper]: ...
-    def get(self, section: str, name: str, default: _D = ..., convert: Callable[[Optional[str]], _T] = ...) -> Union[_T, _D]: ...
+    def get(self, section: str, name: str, default: _D = ..., convert: Callable[[str], _T] = ...) -> Union[_T, _D]: ...
     def lineof(self, section: str, name: Optional[str] = ...) -> Optional[int]: ...
```

**Comment by bluetech** [comment]
Thanks!

**Pull request merged**
