### PR TITLE
py.path.local('/').join('foo') should return '/foo' not '//foo'

### PR DESCRIPTION
**Pull request by AndreasLoow**
See #84!

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@AndreasLoow lol, just as i decided to just od the same - i'd much prefer to merge yours however

**Comment by RonnyPfannschmidt** [comment]
im most curious as to why the build fails now

**Comment by AndreasLoow** [comment]
Not sure ... it fails on the following test:

```
_____________________ TestPOSIXLocalPath.test_join_to_root _____________________
self = <test_local.TestPOSIXLocalPath object at 0x7f0435c9cc88>
path1 = local('/tmp/pytest-of-travis/pytest-0/test_constructor_equality0')
    def test_join_to_root(self, path1):
        root = path1.parts()[0]
        assert len(str(root)) == 1
>       assert str(root.join('a')) == '/a'
E       assert '//a' == '/a'
E         - //a
E         ? -
E         + /a
```

But when I try it locally it works:

```
$ python
Python 3.6.1 (default, Mar 29 2017, 18:15:54)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from py.path import local
>>> path1 = local('/tmp/pytest-of-travis/pytest-0/test_constructor_equality0')
>>> root = path1.parts()[0]
>>> root
local('/')
>>> assert len(str(root)) == 1
>>> root.join('a')
local('/a')
>>> assert str(root.join('a')) == '/a'
```

**Comment by RonnyPfannschmidt** [comment]
@AndreasLoow i determined its the issue i found in #130 - tox-dev/tox#536 is taking a toll on pylib

**Comment by RonnyPfannschmidt** [comment]
merged as the error is urelated and stems from the tox issue

**Pull request merged**
