### PR TITLE
readlines: use mode=r in py3

### PR DESCRIPTION
**Pull request by montefra**
This is the first commit targeting #115.
In the next few days I'll see if the tests give more warnings about mode=U and report here.

### CODE REVIEW

**Comment by montefra** [comment]
I have run tox -e py35 adding pytest-warnings to the dependences list and there is no other warning about ``mode="U"``. I would say that this solves the issue.

**Comment by montefra** [comment]
Would you mind if I add py36 to tox.ini and travis?

**Comment by RonnyPfannschmidt** [comment]
please go ahead, perhaps use a separate pr for that

**Comment by montefra** [comment]
> please go ahead, perhaps use a separate pr for that

done in PR #118

**Pull request merged**
