### PR TITLE
Release 1.4.33 2nd attempt

### PR DESCRIPTION
**Pull request by nicoddemus**
Supersedes #102

### CODE REVIEW

**Comment by nicoddemus** [comment]
Builds:

* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-tester/builds/211119246)
* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-tester/build/1.0.34)

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt I'm not entirely happy with the svn-related errors on Travis. I plan to investigate it a little bit later, but meanwhile do you have any idea of what the problem might be given that `master` passes and only `devpi test` is breaking?

Also, do we have any plans related to the svn functionality? I'm not sure how much it is used and how problematic it is to maintain it.

**Comment by RonnyPfannschmidt** [comment]
i have no plans, it has no maintainer and i recall its broken since a while now, i believe Travis skips them due to no svn

**Comment by nicoddemus** [comment]
RÁ oh my. It was failing because I generated the package on Windows, which left the `testrepo.dump` file with CRLF line endings. Surprisingly, `svnadmin` chokes on the file because of that (which doesn't inspire much confidence since the file is supposed to be TEXT). Fixed by adding a `.gitattributes` which forces that file type to always be checked out as LF line endings, and that seems to fix the tests, at least on Travis.

Other fixes:

* Clean up tox.ini and use tox-travis to run on Travis
  The "external" environment was never run on Travis, that's why it was broken during packaging
* Fix tests to use 'str(exc)' instead of 'exc.msg' for pytest compatibility: in Pytest 3.0 we no longer replace the builtin `AssertionError` with a custom exception which has a `.msg` attribute. The test suite still doesn't execute in pytest>2.9, but is a step in that direction.

Just realized that a lot of tests break when executed

With that the `devpi test` command on Travis [is now green](https://travis-ci.org/nicoddemus/devpi-cloud-tester/builds/211576926), although I doubt it will pass on Windows.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt once you are OK with the changes, I can publish the package and will try to spend a couple of hours cleaning up the test suite so it works on Pytest 3.0.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus if it works im happy ^^

**Pull request merged**
